### ISSUE TITLE
New Flashlight Sound does not function properly.

### ISSUE THREAD

**Issue by ShibberinoShipperino** [SheepFighter/Stratus#17]
Problem Description:
The new flashlight sound does not function when it is activated on and off, plays only when spawned in via game panel.

What did you expect to happen:
Flashlight would play new sound when switched to on/off state.

What happened instead:
Default sound plays.

Why is this bad/What are the consequences:
New Sound does not work, blame my shitcode. 😭 
I'm pretty sure post mortem that I made it so that when the Flashlight initalizes it plays a sound instead of when used, im fukkin dumb 

Steps to reproduce the problem:
Spawn a Flashlight, you will hear the new sound, turning on/off the flashlight makes the old sound.

**Comment by msgerbs** [comment]
I think this is another merge conflict issue. On your branch there was no playsound() anywhere in this file before you added your sounds, but on the Development branch there was a playsound() in the attack_self() proc. So that's where the old sound was coming from. Then your sounds were added, but you added them in the initialize() proc instead of the adjust_brightness() proc which is called when you attack_self() the flightlight to turn it on/off.
